//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_stock_items
    {
        public string whStockItemsEntryBranchCode { get; set; }
        public string warehousesCode { get; set; }
        public string warehousesEntryBranchCode_copy1 { get; set; }
        public string warehousesEntryGroupCode { get; set; }
        public string block { get; set; }
        public string rack { get; set; }
        public string cell { get; set; }
        public string warehouseStockMasterTransactionCode { get; set; }
        public string warehouseStockMasterEntryBranchCode { get; set; }
        public string warehouseStockMasterEntryGroupCode { get; set; }
        public string warehouseStockMasterEntryType { get; set; }
        public string sku { get; set; }
        public string productsEntryGroupCode { get; set; }
        public string lotNumber { get; set; }
        public string serialNo { get; set; }
        public Nullable<System.DateTime> expiryDateTime { get; set; }
        public string qty { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual warehouse_stock_master warehouse_stock_master { get; set; }
        public virtual warehouse_structure warehouse_structure { get; set; }
    }
}
