//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public warehouse()
        {
            this.warehouse_stock_master = new HashSet<warehouse_stock_master>();
            this.warehouse_structure = new HashSet<warehouse_structure>();
            this.warehouses_merge = new HashSet<warehouses_merge>();
            this.warehouses_merge1 = new HashSet<warehouses_merge>();
            this.wearhouse_under_branches = new HashSet<wearhouse_under_branches>();
        }
    
        public string warehousesCode { get; set; }
        public string warehousesEntryBranchCode { get; set; }
        public string warehousesEntryGroupCode { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string CoveringAreas { get; set; }
        public string logitudeLocation { get; set; }
        public string latitudeLoaction { get; set; }
        public string warehouseType { get; set; }
        public string remarks { get; set; }
        public string contactType2 { get; set; }
        public string contactNo2 { get; set; }
        public string contactType1 { get; set; }
        public string contactNo1 { get; set; }
        public string email { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouse_stock_master> warehouse_stock_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouse_structure> warehouse_structure { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouses_merge> warehouses_merge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouses_merge> warehouses_merge1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wearhouse_under_branches> wearhouse_under_branches { get; set; }
    }
}
