//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.warehouse
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_stock_master
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public warehouse_stock_master()
        {
            this.delivery_challan_receive = new HashSet<delivery_challan_receive>();
            this.delivery_challan_send = new HashSet<delivery_challan_send>();
            this.warehouse_stock_items = new HashSet<warehouse_stock_items>();
        }
    
        public string warehouseStockMasterTransactionCode { get; set; }
        public string warehouseStockMasterEntryBranchCode { get; set; }
        public string warehouseStockMasterEntryGroupCode { get; set; }
        public string warehouseStockMasterEntryType { get; set; }
        public string warehousesCode { get; set; }
        public string warehousesEntryBranchCode { get; set; }
        public string warehousesEntryGroupCode { get; set; }
        public string supplierPurchaseOrdersEntryBranchCode { get; set; }
        public Nullable<int> supplierPoNo { get; set; }
        public string supplierPoNoPrefix { get; set; }
        public string supplierPoEntryGroupCode { get; set; }
        public string supplierPurchaseReturnEntryBranchCode { get; set; }
        public Nullable<int> supplierPurchaseReturnNo { get; set; }
        public string supplierPurchaseReturnNoPrefix { get; set; }
        public string supplierPurchaseReturnEntryGroupCode { get; set; }
        public Nullable<int> posPoNo { get; set; }
        public string posPoNoPrefix { get; set; }
        public string posPoEntryGroupCode { get; set; }
        public string posPoFromBranchCode { get; set; }
        public string salesReturnEntryBranchCode { get; set; }
        public Nullable<int> salesReturnNo { get; set; }
        public string salesReturnNoPrefix { get; set; }
        public string salesReturnEntryGroupCode { get; set; }
        public string posInvoiceInvoicesEntryBranchCode { get; set; }
        public string posInvoiceBillNumber { get; set; }
        public string posInvoiceBillPrefix { get; set; }
        public string posInvoiceBillEntryGroupCode { get; set; }
        public string posReturnEntryBranchCode { get; set; }
        public string posReturnNumber { get; set; }
        public string posReturnPrefix { get; set; }
        public string posReturnlEntryGroupCode { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_challan_receive> delivery_challan_receive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<delivery_challan_send> delivery_challan_send { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warehouse_stock_items> warehouse_stock_items { get; set; }
        public virtual warehouse warehouse { get; set; }
    }
}
