//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Employee
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee_merge
    {
        public string employeeMergeEntryBranchCode { get; set; }
        public string employeeEntryBranchCode { get; set; }
        public string employeeCode { get; set; }
        public string employeeEntryGroupCode { get; set; }
        public string employeeEntryBranchCode_copy { get; set; }
        public string employeeCode_copy { get; set; }
        public string employeeEntryGroupCode_copy { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
