//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Employee
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class employeelvitsposdbEntities : DbContext
    {
        public employeelvitsposdbEntities()
            : base("name=employeelvitsposdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<employee_merge> employee_merge { get; set; }
    
        public virtual int getEmployeeWithDynamicClauses(string dynamicWhereClauses, string dynamicOrderByFields, Nullable<int> skip, Nullable<int> take)
        {
            var dynamicWhereClausesParameter = dynamicWhereClauses != null ?
                new ObjectParameter("dynamicWhereClauses", dynamicWhereClauses) :
                new ObjectParameter("dynamicWhereClauses", typeof(string));
    
            var dynamicOrderByFieldsParameter = dynamicOrderByFields != null ?
                new ObjectParameter("dynamicOrderByFields", dynamicOrderByFields) :
                new ObjectParameter("dynamicOrderByFields", typeof(string));
    
            var skipParameter = skip.HasValue ?
                new ObjectParameter("skip", skip) :
                new ObjectParameter("skip", typeof(int));
    
            var takeParameter = take.HasValue ?
                new ObjectParameter("take", take) :
                new ObjectParameter("take", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getEmployeeWithDynamicClauses", dynamicWhereClausesParameter, dynamicOrderByFieldsParameter, skipParameter, takeParameter);
        }
    }
}
