//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikaraksDbContracts.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class asset
    {
        public int idAssets { get; set; }
        public string title { get; set; }
        public string homeBackground { get; set; }
        public string homeAudio { get; set; }
        public string url { get; set; }
    }
}
