//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikaraksDbContracts.DomainModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class chikaraksEntities : DbContext
    {
        public chikaraksEntities()
            : base("name=chikaraksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asset> assets { get; set; }
        public virtual DbSet<content> contents { get; set; }
        public virtual DbSet<errorlog> errorlogs { get; set; }
        public virtual DbSet<registration> registrations { get; set; }
        public virtual DbSet<story_category> story_category { get; set; }
        public virtual DbSet<story_scene_pages> story_scene_pages { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
