//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikaraksDbContracts.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class errorlog
    {
        public int idlogs { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public bool isError { get; set; }
        public string exception { get; set; }
        public string objectAttachment { get; set; }
        public string className { get; set; }
        public string methodName { get; set; }
        public int lineNumber { get; set; }
        public string fileName { get; set; }
        public string eventJson { get; set; }
        public string errorURL { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public bool recordBySystem { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    }
}
