//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikaraksDbContracts.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class registration
    {
        public int idregistration { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string emailAddress { get; set; }
        public string mobileNo { get; set; }
        public string password { get; set; }
        public string otp { get; set; }
        public string udid { get; set; }
        public string deviceType { get; set; }
        public string countryCode { get; set; }
        public string gcmID { get; set; }
        public string apnsID { get; set; }
    }
}
