//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikaraksDbContracts.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class story_scene_pages
    {
        public int idStoryScenePages { get; set; }
        public int idStoryCategory { get; set; }
        public string title { get; set; }
        public string imageUrl { get; set; }
        public string imageUrlStoreLocation { get; set; }
        public string audioUrl { get; set; }
        public string audioUrlStoreLocation { get; set; }
        public string youtubeUrl { get; set; }
        public string youtubeStoreLocation { get; set; }
        public Nullable<int> indexOrder { get; set; }
    
        public virtual story_category story_category { get; set; }
    }
}
