//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChikaraksDbContracts.DomainModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string userName { get; set; }
        public string passwordEncryptionKey { get; set; }
        public string password { get; set; }
        public string sessionID { get; set; }
        public string sessionValue { get; set; }
        public Nullable<System.DateTime> sessionExpireyDateTime { get; set; }
        public Nullable<System.DateTime> sessionCreateTime { get; set; }
        public Nullable<System.DateTime> blockExpiry { get; set; }
        public string userAccountStatus { get; set; }
        public bool isActive { get; set; }
    }
}
