//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Supplier
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_purchase_orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier_purchase_orders()
        {
            this.supplier_invoices = new HashSet<supplier_invoices>();
            this.supplier_purchase_orders_items = new HashSet<supplier_purchase_orders_items>();
        }
    
        public string supplierPurchaseOrdersEntryBranchCode { get; set; }
        public int supplierPoNo { get; set; }
        public string supplierPoNoPrefix { get; set; }
        public string supplierPoEntryGroupCode { get; set; }
        public System.DateTime supplierPoDate { get; set; }
        public string suppliersEntryBranchCode { get; set; }
        public string suppliersCode { get; set; }
        public string suppliersEntryGroupCode { get; set; }
        public string warehousesCode { get; set; }
        public string warehousesEntryBranchCode { get; set; }
        public string warehousesEntryGroupCode { get; set; }
        public string taxMasterTitle { get; set; }
        public string paymentMode { get; set; }
        public System.DateTime deliveryDate { get; set; }
        public string deliveryLocation { get; set; }
        public string deliveryAddress { get; set; }
        public Nullable<decimal> discount { get; set; }
        public string remarks { get; set; }
        public Nullable<decimal> discountInPercentage { get; set; }
        public string termsAndConditions { get; set; }
        public string poStatus { get; set; }
        public Nullable<decimal> shippingAndHandling { get; set; }
        public Nullable<decimal> other { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_invoices> supplier_invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_purchase_orders_items> supplier_purchase_orders_items { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
