//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Supplier
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public supplier()
        {
            this.supplier_payments = new HashSet<supplier_payments>();
            this.supplier_purchase_orders = new HashSet<supplier_purchase_orders>();
            this.suppliers_merge = new HashSet<suppliers_merge>();
            this.suppliers_merge1 = new HashSet<suppliers_merge>();
        }
    
        public string suppliersEntryBranchCode { get; set; }
        public string suppliersCode { get; set; }
        public string suppliersEntryGroupCode { get; set; }
        public string title { get; set; }
        public string shortTitle { get; set; }
        public string status { get; set; }
        public decimal creditLimitDays { get; set; }
        public string creditLimitAmount { get; set; }
        public Nullable<System.DateTime> permanentAccountNumberDate { get; set; }
        public string contactPersonName { get; set; }
        public string contactPersonDesignation { get; set; }
        public string pincode { get; set; }
        public string mobileNo { get; set; }
        public string telephoneNo { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public string registreredAddress { get; set; }
        public string correspondenceAddress { get; set; }
        public string billingAddress { get; set; }
        public string serviceTaxNo { get; set; }
        public string valueAddedTaxNo { get; set; }
        public Nullable<System.DateTime> valueAddedTaxDate { get; set; }
        public string permanentAccountNumber { get; set; }
        public string centralSalesTaxNo { get; set; }
        public Nullable<System.DateTime> centralSalesTaxDate { get; set; }
        public string taxpayerIdentificationNumber { get; set; }
        public Nullable<System.DateTime> taxpayerIdentificationNumberDate { get; set; }
        public string corporateIdentityNumber { get; set; }
        public Nullable<System.DateTime> corporateIdentityNumberDate { get; set; }
        public string bstNo { get; set; }
        public Nullable<System.DateTime> bstDate { get; set; }
        public string registrationNo { get; set; }
        public Nullable<System.DateTime> registrationDate { get; set; }
        public string legalStatus { get; set; }
        public string bankName { get; set; }
        public string bankAcNo { get; set; }
        public string ifsccode { get; set; }
        public Nullable<int> overDueLockingDays { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_payments> supplier_payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_purchase_orders> supplier_purchase_orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suppliers_merge> suppliers_merge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<suppliers_merge> suppliers_merge1 { get; set; }
    }
}
