//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Supplier
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_payments
    {
        public string supplierPaymentsPaymentsEntryBranchCode { get; set; }
        public string supplierPaymentsTransactionCode { get; set; }
        public string supplierPaymentsEntryBranchCode { get; set; }
        public string supplierPaymentsEntryGroupCode { get; set; }
        public string supplierInvoicesEntryBranchCode { get; set; }
        public string supplierInvoiceNumber { get; set; }
        public string suppliersEntryBranchCode { get; set; }
        public string suppliersCode { get; set; }
        public string suppliersEntryGroupCode { get; set; }
        public string supplierPurchaseReturnEntryBranchCode { get; set; }
        public Nullable<int> supplierPurchaseReturnNo { get; set; }
        public string supplierPurchaseReturnNoPrefix { get; set; }
        public string supplierPurchaseReturnEntryGroupCode { get; set; }
        public string reciptReceivedReferenceNumber { get; set; }
        public string paymentAccountsBankName { get; set; }
        public string paymentAccountsAccountNumber { get; set; }
        public string paymentAccountsEntryGroupCode { get; set; }
        public string reciptStatus { get; set; }
        public string transactionType { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> lessAmount { get; set; }
        public string contactPayerNumber { get; set; }
        public string contactPayerAddress { get; set; }
        public string contactPayerName { get; set; }
        public string contactReceiverNumber { get; set; }
        public string contactReceiverAddress { get; set; }
        public string contactReceiverName { get; set; }
        public string paymentType { get; set; }
        public Nullable<System.DateTime> nextPaymentDate { get; set; }
        public string chargesOf { get; set; }
        public string chequeNumber { get; set; }
        public string chequeDate { get; set; }
        public string cardNumber { get; set; }
        public Nullable<int> expiryMonth { get; set; }
        public Nullable<int> expiryYear { get; set; }
        public Nullable<System.DateTime> dueNotificationDate { get; set; }
        public string transferBankname { get; set; }
        public string transferAccountName { get; set; }
        public string transferAccountNumber { get; set; }
        public string transferIfscCode { get; set; }
        public string remarks { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual supplier_invoices supplier_invoices { get; set; }
        public virtual supplier_purchase_return supplier_purchase_return { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
