//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Supplier
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class supplierlvitsposdbEntities : DbContext
    {
        public supplierlvitsposdbEntities()
            : base("name=supplierlvitsposdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<supplier_invoices> supplier_invoices { get; set; }
        public virtual DbSet<supplier_invoices_items> supplier_invoices_items { get; set; }
        public virtual DbSet<supplier_payments> supplier_payments { get; set; }
        public virtual DbSet<supplier_purchase_orders> supplier_purchase_orders { get; set; }
        public virtual DbSet<supplier_purchase_orders_items> supplier_purchase_orders_items { get; set; }
        public virtual DbSet<supplier_purchase_return> supplier_purchase_return { get; set; }
        public virtual DbSet<supplier_purchase_return_items> supplier_purchase_return_items { get; set; }
        public virtual DbSet<supplier> suppliers { get; set; }
        public virtual DbSet<suppliers_merge> suppliers_merge { get; set; }
    
        public virtual int getSuppliersWithDynamicClauses(string dynamicWhereClauses, string dynamicOrderByFields, Nullable<int> skip, Nullable<int> take)
        {
            var dynamicWhereClausesParameter = dynamicWhereClauses != null ?
                new ObjectParameter("dynamicWhereClauses", dynamicWhereClauses) :
                new ObjectParameter("dynamicWhereClauses", typeof(string));
    
            var dynamicOrderByFieldsParameter = dynamicOrderByFields != null ?
                new ObjectParameter("dynamicOrderByFields", dynamicOrderByFields) :
                new ObjectParameter("dynamicOrderByFields", typeof(string));
    
            var skipParameter = skip.HasValue ?
                new ObjectParameter("skip", skip) :
                new ObjectParameter("skip", typeof(int));
    
            var takeParameter = take.HasValue ?
                new ObjectParameter("take", take) :
                new ObjectParameter("take", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("getSuppliersWithDynamicClauses", dynamicWhereClausesParameter, dynamicOrderByFieldsParameter, skipParameter, takeParameter);
        }
    }
}
