//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Branch
{
    using System;
    using System.Collections.Generic;
    
    public partial class branch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public branch()
        {
            this.branches_payments = new HashSet<branches_payments>();
            this.employee_underbranch = new HashSet<employee_underbranch>();
        }
    
        public string branchCode { get; set; }
        public string branchName { get; set; }
        public string description { get; set; }
        public string address { get; set; }
        public string branchIcon { get; set; }
        public string CoveringAreas { get; set; }
        public string logitudeLocation { get; set; }
        public string latitudeLoaction { get; set; }
        public string branchType { get; set; }
        public System.DateTime openDate { get; set; }
        public Nullable<System.DateTime> closeDate { get; set; }
        public string experiance { get; set; }
        public Nullable<decimal> investment { get; set; }
        public Nullable<decimal> deposit { get; set; }
        public string remarks { get; set; }
        public string contactType2 { get; set; }
        public string contactNo2 { get; set; }
        public string contactType1 { get; set; }
        public string contactNo1 { get; set; }
        public string email { get; set; }
        public string city { get; set; }
        public string staticIpAddress { get; set; }
        public string state { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> lastSyncDate { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string branchCodeEntryBranchCode { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<branches_payments> branches_payments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<employee_underbranch> employee_underbranch { get; set; }
    }
}
