//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Branch
{
    using System;
    using System.Collections.Generic;
    
    public partial class branches_payments
    {
        public string BranchCode { get; set; }
        public string branchesPaymentsTransactionCode { get; set; }
        public string branchesPaymentsEntryBranchCode { get; set; }
        public string branchesPaymentsEntryGroupCode { get; set; }
        public string salesInvoicesEntryBranchCode { get; set; }
        public Nullable<int> salesInvoicesNo { get; set; }
        public string salesInvoicesNoPrefix { get; set; }
        public string salesInvoicesNoEntryGroupCode { get; set; }
        public string salesInvoiceToBranchCode { get; set; }
        public string salesReturnEntryBranchCode { get; set; }
        public Nullable<int> salesReturnNo { get; set; }
        public string salesReturnNoPrefix { get; set; }
        public string salesReturnEntryGroupCode { get; set; }
        public string reciptReceivedReferenceNumber { get; set; }
        public string paymentAccountsBankName { get; set; }
        public string paymentAccountsAccountNumber { get; set; }
        public string paymentAccountsEntryGroupCode { get; set; }
        public string reciptStatus { get; set; }
        public decimal amount { get; set; }
        public Nullable<decimal> lessAmount { get; set; }
        public string contactPayerNumber { get; set; }
        public string contactPayerAddress { get; set; }
        public string contactPayerName { get; set; }
        public string contactReceiverNumber { get; set; }
        public string contactReceiverAddress { get; set; }
        public string contactReceiverName { get; set; }
        public string transactionType { get; set; }
        public string paymentType { get; set; }
        public Nullable<System.DateTime> nextPaymentDate { get; set; }
        public string chargesOf { get; set; }
        public string chequeNumber { get; set; }
        public string chequeDate { get; set; }
        public string cardNumber { get; set; }
        public Nullable<int> expiryMonth { get; set; }
        public Nullable<int> expiryYear { get; set; }
        public Nullable<System.DateTime> dueNotificationDate { get; set; }
        public string transferBankname { get; set; }
        public string transferAccountName { get; set; }
        public string transferAccountNumber { get; set; }
        public string transferIfscCode { get; set; }
        public string remarks { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual branch branch { get; set; }
    }
}
