//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_merge
    {
        public string sku { get; set; }
        public string productsEntryGroupCode { get; set; }
        public string sku_copy { get; set; }
        public string productsEntryGroupCode_copy { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string productsMergeEntryBranchCode { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual product product { get; set; }
        public virtual product product1 { get; set; }
    }
}
