//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Product
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.combo_items = new HashSet<combo_items>();
            this.product_price_master = new HashSet<product_price_master>();
            this.products_merge = new HashSet<products_merge>();
            this.products_merge1 = new HashSet<products_merge>();
            this.supplier_product_mapping = new HashSet<supplier_product_mapping>();
        }
    
        public string sku { get; set; }
        public string productsEntryGroupCode { get; set; }
        public string productsEntryBranchCode { get; set; }
        public string taxMasterTitle { get; set; }
        public string product_class_title { get; set; }
        public string title { get; set; }
        public string barcodeNumber { get; set; }
        public string skuParent { get; set; }
        public string productsEntryBranchCodeParent { get; set; }
        public string productsEntryGroupCodeParent { get; set; }
        public Nullable<bool> includeInMenu { get; set; }
        public Nullable<bool> canBeSold { get; set; }
        public Nullable<bool> isCombo { get; set; }
        public Nullable<bool> canPurchase { get; set; }
        public Nullable<System.TimeSpan> makeDuration { get; set; }
        public string unit_of_mesurement_title { get; set; }
        public Nullable<bool> isCategory { get; set; }
        public string productDescription { get; set; }
        public Nullable<decimal> stockWarningQty { get; set; }
        public Nullable<bool> availableOnEcommerce { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<combo_items> combo_items { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_price_master> product_price_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_merge> products_merge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<products_merge> products_merge1 { get; set; }
        public virtual unit_of_mesurement unit_of_mesurement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplier_product_mapping> supplier_product_mapping { get; set; }
    }
}
