//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Configuration
{
    using System;
    using System.Collections.Generic;
    
    public partial class delete_logs
    {
        public string keys { get; set; }
        public string databaseName { get; set; }
        public string tableName { get; set; }
        public string deleteJSON { get; set; }
        public System.DateTime entryDate { get; set; }
        public string deleteRoutePoint { get; set; }
        public string syncGUID { get; set; }
    }
}
