//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.User
{
    using System;
    using System.Collections.Generic;
    
    public partial class override_access_role
    {
        public string domain { get; set; }
        public string controller { get; set; }
        public string view { get; set; }
        public string userName { get; set; }
        public string userEntryGroupCode { get; set; }
        public string userEntryBranchCode { get; set; }
        public bool canAccess { get; set; }
        public bool visible { get; set; }
        public string title { get; set; }
        public bool permanent { get; set; }
        public Nullable<System.DateTime> overrideTill { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual access_area access_area { get; set; }
        public virtual user user { get; set; }
    }
}
