//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.User
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.override_access_role = new HashSet<override_access_role>();
            this.user_settings = new HashSet<user_settings>();
        }
    
        public string accessRoleTitle { get; set; }
        public string userName { get; set; }
        public string userEntryGroupCode { get; set; }
        public string userEntryBranchCode { get; set; }
        public string employeeEntryBranchCode { get; set; }
        public string employeeCode { get; set; }
        public string employeeEntryGroupCode { get; set; }
        public string branchCode { get; set; }
        public string userStatus { get; set; }
        public string userAccountStatus { get; set; }
        public string passwordEncryptionKey { get; set; }
        public string password { get; set; }
        public System.DateTime lastLogin { get; set; }
        public Nullable<System.DateTime> lastPasswordResetDate { get; set; }
        public Nullable<System.DateTime> blockExpiry { get; set; }
        public int warnOnFailedLoginAfterAtttempt { get; set; }
        public bool isLion { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string sessionID { get; set; }
        public string sessionValue { get; set; }
        public Nullable<System.DateTime> sessionExpireyDateTime { get; set; }
        public Nullable<System.DateTime> sessionCreateTime { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual access_role_master access_role_master { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<override_access_role> override_access_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user_settings> user_settings { get; set; }
    }
}
