//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.User
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_settings
    {
        public string userName { get; set; }
        public string userEntryGroupCode { get; set; }
        public string userEntryBranchCode { get; set; }
        public string title { get; set; }
        public string values { get; set; }
        public string description { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual user user { get; set; }
    }
}
