//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Account
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class accountinglvitsposdbEntities : DbContext
    {
        public accountinglvitsposdbEntities()
            : base("name=accountinglvitsposdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_entry_note> account_entry_note { get; set; }
        public virtual DbSet<account_entry_type> account_entry_type { get; set; }
        public virtual DbSet<discount> discounts { get; set; }
        public virtual DbSet<payment_accounts> payment_accounts { get; set; }
        public virtual DbSet<payment_accounts_merge> payment_accounts_merge { get; set; }
        public virtual DbSet<product_class> product_class { get; set; }
        public virtual DbSet<recipt> recipts { get; set; }
        public virtual DbSet<service_charge> service_charge { get; set; }
        public virtual DbSet<tax_details> tax_details { get; set; }
        public virtual DbSet<tax_master> tax_master { get; set; }
    }
}
