//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Account
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public string discountEntryBranchCode { get; set; }
        public string entryGroupCode { get; set; }
        public string discountTitle { get; set; }
        public string functions { get; set; }
        public string discountType { get; set; }
        public string discountCode { get; set; }
        public Nullable<bool> passwordRequired { get; set; }
        public Nullable<bool> taxed { get; set; }
        public Nullable<System.DateTime> mondayFrom { get; set; }
        public Nullable<System.DateTime> tuesdayFrom { get; set; }
        public Nullable<System.DateTime> wednesdayFrom { get; set; }
        public Nullable<System.DateTime> thursdayFrom { get; set; }
        public Nullable<System.DateTime> fridayFrom { get; set; }
        public Nullable<System.DateTime> saturdayFrom { get; set; }
        public Nullable<System.DateTime> sundayFrom { get; set; }
        public Nullable<System.DateTime> mondayTo { get; set; }
        public Nullable<System.DateTime> tuesdayTo { get; set; }
        public Nullable<System.DateTime> wednesdayTo { get; set; }
        public Nullable<System.DateTime> thursdayTo { get; set; }
        public Nullable<System.DateTime> fridayTo { get; set; }
        public Nullable<System.DateTime> saturdayTo { get; set; }
        public Nullable<System.DateTime> sundayTo { get; set; }
        public Nullable<System.DateTime> effectiveFrom { get; set; }
        public Nullable<System.DateTime> effectiveTo { get; set; }
        public Nullable<bool> isOnWholesale { get; set; }
        public Nullable<decimal> maximumAmount { get; set; }
        public Nullable<decimal> minimumAmount { get; set; }
        public Nullable<bool> applyOnBaseProduct { get; set; }
        public string qualificationType { get; set; }
        public string qualificationSubType { get; set; }
        public string qualifyingGroup { get; set; }
        public string applyToWeightedProduct { get; set; }
        public Nullable<decimal> bogo { get; set; }
        public Nullable<int> minimumPoints { get; set; }
        public string discountForProducts { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    }
}
