//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Account
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_accounts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public payment_accounts()
        {
            this.account_entry_note = new HashSet<account_entry_note>();
            this.payment_accounts_merge = new HashSet<payment_accounts_merge>();
            this.payment_accounts_merge1 = new HashSet<payment_accounts_merge>();
        }
    
        public string paymentAccountsBankName { get; set; }
        public string paymentAccountsAccountNumber { get; set; }
        public string paymentAccountsEntryGroupCode { get; set; }
        public string paymentAccountsEntryBranchCode { get; set; }
        public string accountHolderName1 { get; set; }
        public string accountHolderName2 { get; set; }
        public string accountHolderName3 { get; set; }
        public string accountName { get; set; }
        public string bankBranch { get; set; }
        public string ifscCode { get; set; }
        public decimal openingBalance { get; set; }
        public string cardNumber { get; set; }
        public Nullable<int> expiryMonth { get; set; }
        public Nullable<int> expiryYear { get; set; }
        public Nullable<bool> accountStatus { get; set; }
        public string remarks { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_entry_note> account_entry_note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_accounts_merge> payment_accounts_merge { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<payment_accounts_merge> payment_accounts_merge1 { get; set; }
    }
}
