//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LionPOSDbContracts.DomainModels.Account
{
    using System;
    using System.Collections.Generic;
    
    public partial class recipt
    {
        public string reciptPrefix { get; set; }
        public int reciptsNumber { get; set; }
        public string reciptsEntryGroupCode { get; set; }
        public string reciptType { get; set; }
        public string reciptsEntryBranchCode { get; set; }
        public string BranchCode { get; set; }
        public string branchesPaymentsTransactionCode { get; set; }
        public string branchesPaymentsEntryBranchCode { get; set; }
        public string branchesPaymentsEntryGroupCode { get; set; }
        public string accountEntryNoteTransactionCode { get; set; }
        public string accountEntryNoteEntryBranchCode { get; set; }
        public string accountEntryNoteEntryGroupCode { get; set; }
        public string supplierPaymentsTransactionCode { get; set; }
        public string supplierPaymentsEntryBranchCode { get; set; }
        public string supplierPaymentsEntryGroupCode { get; set; }
        public string warehouseStockMasterTransactionCode { get; set; }
        public string warehouseStockMasterEntryBranchCode { get; set; }
        public string warehouseStockMasterEntryGroupCode { get; set; }
        public string warehouseStockMasterEntryType { get; set; }
        public bool isActive { get; set; }
        public bool isDeleted { get; set; }
        public System.DateTime entryDate { get; set; }
        public System.DateTime lastChangeDate { get; set; }
        public bool recordByLion { get; set; }
        public string entryByUserName { get; set; }
        public string changeByUserName { get; set; }
        public string insertRoutePoint { get; set; }
        public string updateRoutePoint { get; set; }
        public string syncGUID { get; set; }
    
        public virtual account_entry_note account_entry_note { get; set; }
    }
}
